### ISSUE TITLE
externalTrafficPolicy in nginx-service.yaml template

### ISSUE THREAD

**Issue by burandobata** [astronomer/astronomer#1035]
Hey,

in nginx-service.yaml template of nginx chart we have possibility to set externalTrafficPolicy to "Cluster" only which is a default and doesn't make sense. This should allow to switch it to "Local". Can this switch be added?

I'm referring to this part:
  {{- if .Values.preserveSourceIP }}
  externalTrafficPolicy: "Cluster"
  {{- end }}

**Comment by danielhoherd** [comment]
https://github.com/astronomer/astronomer/blob/0d69295ca7/charts/nginx/templates/nginx-service.yaml#L40-L42

**Comment by danielhoherd** [comment]
It used to be `Local` https://github.com/astronomer/astronomer/commit/33431136b204601a97783a62ff139e08236473aa and I'm not sure why it changed. [The default does indeed appear to be `Cluster`](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip) and the only alternate value appears to be `Local`.

@schnie @jpweber any comments on this one? It seems like this should be done as an if/else block. Also, as noted by @burandobata, it seems that currently the condition isn't making a difference because it is just explicitly setting what is already the default. [We have it set to False in the chart](https://github.com/astronomer/astronomer/blob/0d69295ca7/charts/nginx/values.yaml#L51), which is a consideration for rolling out any changes to this section.

**Comment by jpweber** [comment]
In a lot of cases people will want this to be local. As noted in the original comment this simply doesn't work. If you want to preserve the source IP you use `local` not `cluster`.  The logic of the if statement should be flipped.  `if .Values.preserveSourceIP` == true use `local`;  else use default (`cluster`)

**Comment by danielhoherd** [comment]
Status update: this feature got caught in limbo due to lack of trustworthy testing. We have since switched to pytest where tests are *much* more reliable, but have not revisited this issue.

**Comment by danielhoherd** [comment]
This was merged today and will go into 0.29.1.
