### ISSUE TITLE
Add RBAC screen(s) in Orbit

### ISSUE THREAD

**Issue by schnie** [astronomer/astronomer#283]
For users to actually take advantage of our integration with Airflow RBAC we should give them the ability to assign roles to other users in Orbit. Depending on how we actually implement this we may want to also remove the block of code introduced here: https://github.com/astronomer/houston-api/pull/40/files.

Depends on https://github.com/astronomer/astronomer/issues/244

**Comment by schnie** [comment]
@ashb, chatted with @ryw and @vparekh94 today about the things we were also discussing yesterday. After talking through some users stories (@vparekh94 following up with), this seemed like a good MVP of the RBAC integration. I think we roughly landed in a similar place, debating if we should manage users at two levels. This time around we ended up with thinking management at both levels, would be the best way, possibly adding some shortcuts at workspace level later...

Modify existing _Workspace_ level user screen and invite system to allow _Workspace Admins_ to select a _Workspace Role_ when inviting a new user, also allowing admins to edit the role that user has. Default to the lowest level (viewer).

Add users tab down to _Deployment_ level. This screen allows _Deployment Admins_ to select from a dropdown of users that exist within the _Workspace_ already. This should be paired with another dropdown that lets users select the _Deployment Role_ for that user.

All users should be able to see the "users" tabs, but only admins can modify, the dropdowns should be disabled for non admin users.

@ashb does this seem good to you? Anything you'd want to change or don't like?

**Comment by vparekh94** [comment]
Some user stories for this:

*Only admins can create workspaces:*

As a user, I want to invite someone to Airflow so that they can deploy DAGs to deployment x. However, we don't want to give everyone the ability to spin up Airflow deployments, even in their own workspace, unless I explicitly give them access to.

*Workspace Admin*:
As a user, I've just had my dev-ops team set up Astronomer. I'm the technical lead on a project and I want to the workspace for my project. I'll do this through the Users tab at the workspace level, where each user will be invited with the lowest level (viewer only) unless otherwise specified (Workspace Editor, Workspace Admin) .


*Deployment Admin*
As a user, I'm a workspace admin and have invited a few users to my workspace. I'll add users at the _deployment_ level in the Deployment view since access to different environments will vary greatly in a team.

**Comment by schnie** [comment]
And we might want this behind a new config. We'll likely want cloud mode to stay as is.

**Comment by ashb** [comment]
Plan we've come up with after a call on this:

### Houston:
-  create one mutation per type, for example `setDeploymentRoleBinding(deyploymentId! userId!, Role)`

    This lets us use more direct/granular `@auth(permission: "deployment.iam.update")` statements and have it be explicit in the schema what permissions are required.

    This one mutation will create/update/delete the role bindings for this user to the desired state (since right now a roles are additive we don't need the ability to be in multiple roles for an Entity (workspace/deployment)

    Role is "optional" in the sig to allow setting it to none/null to remove permissions

- Probably add `roleBindings{}` to the deployments, workspaces, and user queries to get the info needed to populate the screens in Orbit. (Do we want to limit these fields to only admins?

### Obit

- Add permmissions management to:
    * Workspace: Two: admin, viewer
    * Deployment: Four options: Admin, Editor, Viewer, No Access
- We will add permissions controls to these screens :
    * Per User screen: Configure role in workspace, and role in each deployment in the workspace
    * Per Workspace level: list all users in the workspace and list the roles they have in this workspace
    * Per Deployment level: list all users in the deployment and control what permissions the users have.

Anything mentioning "User" should probably equally apply to service accounts. That may complicate the queries/mutations :(

**Comment by ryw** [comment]
Discussion w/ @schnie 

1. Let's only admin user roles @ workspace layer for now. Deployment roles will cascade from Workspace. Airflow roles will cascade from Deployment.

2. On the CLI thought experiment front, here's what we'd want:

* Modify `astro workspace user list` to show roles
* Modify `astro workspace user add EMAIL -r ROLE` so that default role is VIEWER, and set the role based on the flag
* Create `astro workspace user update-role EMAIL ROLE` or `astro workspace user update EMAIL -r ROLE` to update user role the the new role

Also discussed w/ @schnie that we will work to refactor houston `deployments` and `users` queries very soon.

**Comment by schnie** [comment]
If we're cool to move forward with this for our RBAC release, we should be able to get away with only adding a dropdown `menu` to the user page at the workspace level, and not including any deployment level UI components, which simplifies things. Same would go for ServiceAccounts.

**Comment by vparekh94** [comment]
@ryw yeah - I think that works for me. 

Previously, we ran into the use case of:

"As a system admin, I need to delete some rogue deployments. I would like to do this from the UI, so the API will take care of removing it completely (from helm and the db), so I need a way to force myself into a workspace"

Seems like this would alleviate 90% of that pain point because not everyone would be able to create deployments. 

Would we add a way for sys admins (access to grafana+kibana) to be able to jump into workspaces down the line?

**Comment by ashb** [comment]
Note to self: `astro workspace user add EMAIL -r ROLE` will need extra data modelling to store the role-to-be if we need to send out an invite.

**Comment by andriisoldatenko** [comment]
related issues in astro-cli repo https://github.com/astronomer/astro-cli/issues/212

**Comment by petedejoy** [comment]
PR [open here](https://github.com/astronomer/orbit-ui/pull/72) that includes:

- UserConfigure page to control user roles at the workspace level.
- Error handling throughout the application so you get a snackbar error if you don't have appropriate permissions for something you're trying to do.
<img width="1792" alt="Screen Shot 2019-05-10 at 2 07 46 PM" src="https://user-images.githubusercontent.com/32076749/57547719-15531600-732d-11e9-89ff-d0a026e1047a.png">
