### ISSUE TITLE
Shared tenancy resources.

### ISSUE THREAD

**Issue by TZubiri** [astronomer/astronomer#348]
**Is your feature request related to a problem? Please describe.**
Price and maintenance costs are still somewhat high.

**Describe the solution you'd like**
Transferring ownership of Airflow components to Astronomer. Sharing the physical resources amongst multiple users, and charging for the service, not the resources. A simple example to migrate would be the webserver, I don't think there are many differences between customer in this component, the service is cheap at 20$ per month, but if I understand correctly, it reserves 0.2 CPUs and 0.7GB of RAM per user, which is mostly spent idle. By making it shared, this could be reduced to (eyeballing) virtually zero. Another advantage of this approach is that users wouldn't have to monitor or deploy this service.

**Additional context**
I'm not sure whether this is feasible, but I'm curious as to whether this solution had been considered in the past, and if so, and why it was rejected.

Thank you!

**Comment by schnie** [comment]
Hey @TZubiri, the reason everything is totally separate and isolated now is pretty much due to how Airflow is designed. Currently, the Airflow Webserver and Scheduler and Workers all parse the DAG files in some form and therefore are heavily dependent on the end users code and dependencies.

Astronomer and the Airflow community are currently tackling a few issues to make this less of an issue, including splitting DAG parsing to its own service, freeing up the scheduler to purely scheduler and letting the webserver become stateless.

As new features become available, Astronomer will take full advantage of them and we'll continue to drive features that drive the baseline cost of an Airflow instance down.
