### ISSUE TITLE
DAG gone it! Free trail + email alerting

### ISSUE THREAD

**Issue by sjmiller609** [astronomer/astronomer#394]
**Describe the bug**
See this issue https://github.com/astronomer/terraform-google-astronomer-cloud/issues/18

**Expected behavior**
Either allow for this capability in free trial, or provide an informative error message

**Comment by ryw** [comment]
We should allow alerts in trial

**Comment by petedejoy** [comment]
Thanks for tracking this down, @sjmiller609! The issue here is that the resolver powering the alerts tab is the `updateDeployment` mutation. We block certain aspects of that while a workspace is in trial mode.

Per some conversations we've had recently around GraphQL best practice, we really want to create a new resolver for every action that a user can take in the application- it is probably not great that adding an alert is bundled into the logic of that bulkier mutation. There's probably a way to build in a band-aid solution that allows the mutation to run in its current state, but I'd prefer building a separate `deploymentAddAlert` mutation to cover this functionality rather than spending time building a temporary solution. @schnie what do you think?

**Comment by schnie** [comment]
Yep, should be its own mutation. We'll continue to break the big mutations and queries up as we go.

**Comment by petedejoy** [comment]
Closing this issue in favor of https://github.com/astronomer/houston-api/issues/100
