### ISSUE TITLE
Feature Request: Env Var that lists Deployment Namespace

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/astronomer#405]
**Is your feature request related to a problem? Please describe.**

To [instantiate the KubePodOperator on Astronomer](https://www.astronomer.io/docs/kubepodoperator/), you need to list the underlying Kubernetes Namespace that that deployment sits on top of. That namespace isn't clear to both Enterprise and Cloud customers (especially once we have multiple cloud environments).

E.g. For an Enterprise user - if the admin within an org deployed the base platform to a namespace called `base-astro`, and a user on the platform is running on `newtonian-rotation-2937`, that user might not know that their namespace is `base-astro-newtonian-rotation-2937`.

**Describe the solution you'd like**

Add a supported Environment Variable by default to our platform that'd be something like - 

```
ENV DEPLOYMENT_NAMESPACE="geometrical-inclination-3527"
```

**Additional Notes**

That way when users use the KubePodOperator they could do `os.getenv()`. Outside of the KubePodOperator, there are other reasons a user might need to reference their deployment namespace.

**Comment by schnie** [comment]
@paolaperaza this variable is already being injected into the Airlfow config via a Kubernetes `ConfigMap`. This way we can mount the same `airflow.cfg` file into the different Airflow pods. https://github.com/astronomer/helm.astronomer.io/blob/master/charts/airflow/templates/configmap.yaml#L46-L47

Rather than going directly after an environment var, they could use Airflows configuration to get the value instead. This way it will respect the full chain of default config, then `airflow.cfg`, then env vars.

I think it'd look something like:
```python
from airflow import configuration as conf
namespace = conf.get('kubernetes', 'NAMESPACE')
```

**Comment by ryw** [comment]
@paolaperaza want to move this in the forum?

**Comment by paolaperaza** [comment]
@schnie Ah, that's super helpful. Thanks!

@ryw I just spun up a docs issue separately to cover this within our existing [KubernetesPodOperator Doc](https://www.astronomer.io/docs/kubepodoperator/) -  https://github.com/astronomer/docs/issues/125

If you guys think that covers it, feel free to close out this issue.
