### ISSUE TITLE
Deployments getting mixed up

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#436]
1. Make workspace "Foo"
1. Make deployment "Foo"
1. Make workspace "Goo"
1. Make deployment "Goo"
1. "Goo" is in both workspaces, I can't see deployment "Foo" anymore.

**Comment by petedejoy** [comment]
Looks like this was caused by some of the changes we made to the `workspaces` query. Right here, specifically: https://github.com/astronomer/orbit-ui/pull/140/files#diff-70e8192191f541048dc7b6c0f1eafdbcR12

We changed the query to not take an input and return all workspaces a user has access to rather than a singular one give uuid. I think we'll need to create a separate `workspace` query to handle returning info for a single one, but there may be a hotfix we can get in here. Let me dig in.

**Comment by petedejoy** [comment]
Temporary fix in https://github.com/astronomer/orbit-ui/pull/145
