### ISSUE TITLE
Don't rolling restart webserver

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#445]
After deploying new dags, i can't toggle them in UI. It's because more than 1 webserver is up during restart. It'd be better to get an "Airflow is starting up" message during this time.

<img width="1379" alt="Screen Shot 2019-08-22 at 3 57 32 PM" src="https://user-images.githubusercontent.com/4283/63546062-dc633980-c4f6-11e9-906c-711b0d1f591c.png">

<img width="1386" alt="Screen Shot 2019-08-22 at 3 56 19 PM" src="https://user-images.githubusercontent.com/4283/63546066-df5e2a00-c4f6-11e9-894b-46572606a3b1.png">

<img width="1366" alt="Screen Shot 2019-08-22 at 3 50 28 PM" src="https://user-images.githubusercontent.com/4283/63546077-e5eca180-c4f6-11e9-83a3-1bbae74c5a8a.png">

**Comment by schnie** [comment]
@ianstanton this may be one we can look at soon for v0.10.1. I think we can change the `RollingRestart` behavior or the webserver to enable this kind of behavior.

**Comment by ianstanton** [comment]
We have two options here:
1. `.spec.strategy.type==Recreate`
    * The existing webserver pod is killed before the new webserver pod is created
2. `.spec.strategy.type==RollingUpdate` with `.spec.strategy.rollingUpdate.maxUnavailable` set to 1
    * The existing webserver pod is killed at the same time the new webserver pod is created

Option 1 will ensure that there are never two webservers running at once, but it would be a bit slower because the new webserver creation won't start until the termination of the existing webserver has completed.

@ryw @schnie which do you guys prefer?

More information here: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy

**Comment by ryw** [comment]
Seems like #2 is worth trying.

**Comment by schnie** [comment]
I'd say let's just do 2.

**Comment by ianstanton** [comment]
No PR yet, just wanted to get something up to a branch. I can change that to option 2 :)

**Comment by ianstanton** [comment]
Here is the behavior we see with option 2:

![no-rolling-webserver](https://user-images.githubusercontent.com/8935584/64156333-da717280-ce34-11e9-8bfb-2bc90995f396.png)

**Comment by ryw** [comment]
Yes that’s ok / expected.

**Comment by ianstanton** [comment]
Resolved with astronomer/helm.astronomer.io#182
