### ISSUE TITLE
airflow user cannot write to tmp folder

### ISSUE THREAD

**Issue by shlomiken** [astronomer/astronomer#513]
Hi
as far as i saw - all folders on the docker image are created and owned by root
including tmp folder 
therefore airflow user cannot write there ,
its very common to download and extract tar.gz files - and extracting them to airflow home
looks weird and messy (consider this is our source folder when developing)
if possible the /tmp directory should be able to be accessible to all users

**Comment by paolaperaza** [comment]
Hey @shlomiken ! Hope you're well 😊  I'm doing some cleanup in our GH repos and seeing that this issue is still open. I'm going to go ahead and close this out since it's not the best place to get support from our team, but if you're still experiencing the above we're happy to help.

You can always:
- Post on our [Community Forum](forum.astronomer.io)
- Reach out to our [Support Team](https://support.astronomer.io)
